let a = 'hello';
console.log(a);
alert(a);
document.write(a);
let b = 'owu';
console.log(b);
alert(b);
document.write(b);
let c = 'com';
console.log(c);
alert(c);
document.write(c);
let d = 'ua';
console.log(d);
alert(d);
document.write(d);
let e = 1;
console.log(e);
alert(e);
document.write(e);
let f = 10;
console.log(f);
alert(f);
document.write(f);
let g = -999;
console.log(g);
alert(g);
document.write(g);
let h = 123;
console.log(h);
alert(h);
document.write(h);
let i = 3.14;
console.log(i);
alert(i);
document.write(i);
let j = 2.7;
console.log(j);
alert(j);
document.write(j);
let k = 16;
console.log(k);
alert(k);
document.write(k);
let l = true;
console.log(l);
alert(l);
document.write(l);
let m = false;
console.log(m);
alert(m);
document.write(m);

let firstName = 'Vitalii';
let middleName = 'Yuriyovych';
let lastName = 'Turkevych';
let person = console.log(`${firstName} ${middleName} ${lastName}`);
console.log(firstName + ' ' + middleName + ' ' + lastName);


let a_1 = 100;
let b_1 = '100';
let c_1 = true;
console.log(a_1, b_1 ,c_1, typeof a_1, typeof b_1, typeof c_1);

let myName = prompt('What is your Name?');
let myMiddleName = prompt('What is your Middle Name?');
let myAge = prompt('What is your Age?');
console.log(`Your Name is ${myName}. Your Middle Name is ${myMiddleName}. Your Age is ${myAge}.`);
